stages:
  - build
  - release

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - python --version
  - pip install build

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest

build-python:
  stage: build
  image: python:3.12
  script:
    - python -m build

release-python:
  stage: release
  image: python:3.12
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
  script:
    - echo "Release step for tag $CI_COMMIT_TAG"
    - ls dist/
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz