stages:
  - build
  - release

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  #DOCKER_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DOCKER_IMAGE: registry.teadal.ubiwhere.com/teadal-public-images/asg-runtime:0.0.1
  DOCKER_USER_NAME: CI-token

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  # override (empty) the global before_script
  before_script: []
  script:
    - docker login -u "$DOCKER_USER_NAME" -p "$REGISTRY_PASSWORD" "https://registry.teadal.ubiwhere.com"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

build-python:
  stage: build
  image: python:3.12
  before_script:
    - python --version
    - pip install build
  script:
    - python -m build

release-python:
  stage: release
  image: python:3.12
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
  before_script:
    - python --version
    - pip install build
  script:
    - echo "Release step for tag $CI_COMMIT_TAG"
    - ls dist/
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
