name: Build Python Package

on:
  push:
    branches: [ "main" ]  

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"  # or whatever you target

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
